import apiClient from './client';

/**
 * Search Queries API service
 */
export const searchApi = {
  /**
   * Execute a search query
   * Note: This creates a search query record. The actual search results
   * will come from the RAG/vector search backend (to be implemented by Caleb/Nate)
   */
  async search(queryText, organizationId, userId) {
    const searchData = {
      organizationId,
      userId,
      queryText,
      queryEmbedding: null, // Will be generated by backend
      resultsCount: 0, // Will be updated after search completes
      latencyMs: null,
      clickedResultIds: null,
    };

    return await apiClient.post('/api/searchqueries', searchData);
  },

  /**
   * Get search query history
   */
  async getHistory() {
    return await apiClient.get('/api/searchqueries');
  },

  /**
   * Update search query with results
   */
  async updateResults(queryId, resultsCount, latencyMs) {
    return await apiClient.put(`/api/searchqueries/${queryId}`, {
      resultsCount,
      latencyMs,
    });
  },

  /**
   * Track clicked result
   */
  async trackClick(queryId, clickedResultIds) {
    return await apiClient.put(`/api/searchqueries/${queryId}`, {
      clickedResultIds,
    });
  },
};
